### ISSUE TITLE
Script Time Delay/Offset Suggestion

### ISSUE THREAD

**Issue by npang** [joshuaptfan/KF2-drop-farm#1]
Hi there,

First of all thank you very much for making this - your script has been working great and I'm glad you're still updating it.

I have one suggestion - is it possible to add a user specified time delay to the user input section of it? I'll typically cancel the script to play for a night time session spanning a few hours, and sometimes I get a drop during that play time. It would be nice to see an extra input question in the start that asks for how long the script should offset before starting up.

So for example, I cancel the script before I start playing KF2 for a few hours (so I don't suddenly load into Zed Landing, suicide, and exit the game), and I get a drop after finishing a game. I play for an hour after that and decide to call it a night. At this point, I have about 2 hours left before I need to begin my 30 minute idle. With the current script, my options are to set a timer for 2 hours, and then launch the script manually with the 30 minute idle, or just launch the script as is and lose some time.

Anyways, just a thought. I appreciate the work you've put into this. It's been very very helpful 👍

**Comment by joshuaptfan** [comment]
Thanks for using my script. It initially had this feature, which I actually removed [earlier](https://github.com/joshuaptfan/KF2-drop-farm/commit/b06fb3c6efccef2865a6bb2b4ed652d0bd44b21c) because I weighed that the prompt was not useful frequently enough to offset its annoyance factor. I've added it back.
